
export EXPECTED_DISTRO="Ubuntu"
export EXPECTED_DIST_VER="22.04"
export EXPECTED_DIST_CODENAME="jammy"
export EXPECTED_ROCM_VER="7.2"
EXPECTED_ROCMVER_REGEX="$(printf "%s" "${EXPECTED_ROCM_VER}.[0-9]+" | sed 's/\./\\./g')"
export EXPECTED_ROCMVER_REGEX

